name: ci-python

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:

  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ] #, windows-2019 ]
        python-version: [ '3.7', '3.8', '3.9' ]  # 'pypy-3.7' no tracemalloc

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: |
        python -m pip install --upgrade wheel setuptools
        python -m pip install --upgrade pybind11

    - name: Python version
      run: python -c "import sys; print(sys.version)"

    - name: "build: setup.py"
      run: |
        cd python
        python setup.py build

    - name: "build: ci-smoketest.py"
      shell: bash
      run: |
        cd tests

        python -c "import subprocess; import sys; retcode = subprocess.call([sys.executable, 'ci-smoketest.py']); print('Exit code', retcode); sys.exit(retcode)"
        rm -rf fce/ci-smoketest_1.fce

    - name: remove local build
      shell: bash
      run: |
        cd python
        rm -rf build dist fcecodec.egg-info

    - name: "install: setup.py"
      run: |
        cd python
        python setup.py install
        
    - name: "install: ci-smoketest.py"
      shell: bash
      run: |
        cd tests

        python -c "import subprocess; import sys; retcode = subprocess.call([sys.executable, 'ci-smoketest.py']); print('Exit code', retcode); sys.exit(retcode)"
        rm -rf fce/ci-smoketest_1.fce
