name: macos

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
        python-version: [ '3.7', '3.8', '3.9' ]  # 'pypy-3.7' no tracemalloc

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: |
        python -m pip install --upgrade pip wheel setuptools pybind11

    - name: Python version
      run: python -c "import sys; print(sys.version)"

    - name: "build: setup.py"
      run: |
        cd python
        python setup.py build

    - name: "pip install: setup.py"
      run: |
        python -m pip install --verbose ./python

    - name: "install: print help"
      shell: bash
      run: |
        python -c "import fcecodec; help(fcecodec)"

    - name: "Add numpy; install: ci-smoketest.py"
      shell: bash
      run: |
        python -m pip install --upgrade numpy

        cd tests
        python -c "import subprocess; import sys; retcode = subprocess.call([sys.executable, 'ci-smoketest.py']); print('Exit code', retcode); sys.exit(retcode)"
        rm -rf fce/ci-smoketest.fce fce/ci-smoketest.fce4 fce/ci-smoketest.fce4m

    - name: "install: ci-diff.py (reproducible fce output)"
      shell: bash
      run: |
        cd tests
        chmod +x ci-diff.py.sh
        ./ci-diff.py.sh
        
