name: windows

on:
  workflow_dispatch:

  push:
    branches:
  pull_request:
    branches:

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        python-version: [ "3.8", "3.11" ]

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: "pip install"
      shell: bash
      run: |
        export PYMEM_MALLOC=""
        python -m pip install --verbose .

    - name: "Print fcecodec.__version__, help"
      shell: bash
      run: |
        echo "import fcecodec as fc; print(f'import fcecodec as fc; fc.__version__={fc.__version__}')" > _version.py; cat _version.py
        python -c "import subprocess; import sys; retcode = subprocess.call([ sys.executable, '_version.py' ]); print('Exit code', retcode); sys.exit(0)"
        python -c "import fcecodec as fc; help(fc)"

    - name: "Install numpy pytest wurlitzer"
      shell: bash
      run: |
        python -m pip install numpy
        python -m pip install pytest
        python -m pip install wurlitzer

    - name: "pytest"
      shell: bash
      run: |
        pytest -s -vv
